# Generated by Django 5.2.1 on 2026-02-02 08:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Guest',
            fields=[
                ('gid', models.IntegerField(primary_key=True, serialize=False)),
                ('gname', models.CharField(max_length=50)),
                ('gemail', models.EmailField(max_length=254, unique=True)),
                ('gmob_no', models.BigIntegerField(unique=True)),
                ('gid_proof', models.BigIntegerField(unique=True)),
                ('address', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('rid', models.IntegerField(primary_key=True, serialize=False)),
                ('room_no', models.IntegerField(unique=True)),
                ('room_type', models.CharField(max_length=20)),
                ('price_per_day', models.BigIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Grust_login',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gl_id', models.IntegerField(auto_created=True)),
                ('gl_password', models.CharField(max_length=12)),
                ('gid_proof', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hotelapp.guest')),
            ],
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bid', models.IntegerField()),
                ('check_in', models.DateField()),
                ('check_out', models.DateField()),
                ('total_day', models.IntegerField()),
                ('status', models.CharField(max_length=50)),
                ('gid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hotelapp.guest')),
                ('rid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hotelapp.room')),
            ],
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pid', models.IntegerField()),
                ('amount', models.IntegerField()),
                ('payment_mode', models.CharField(max_length=50)),
                ('paid', models.BooleanField()),
                ('payment_date', models.DateField()),
                ('bid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hotelapp.booking')),
            ],
        ),
    ]
