# Generated by Django 5.2.1 on 2026-02-03 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotelapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='guest',
            name='gl_password',
            field=models.CharField(default=models.BigIntegerField(unique=True), max_length=100),
        ),
        migrations.DeleteModel(
            name='Grust_login',
        ),
    ]
