# Generated by Django 5.2.1 on 2026-02-04 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotelapp', '0004_alter_room_room_no'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='room_no',
            field=models.IntegerField(),
        ),
    ]
