# Generated by Django 5.2.1 on 2026-02-05 19:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotelapp', '0005_alter_room_room_no'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='rid',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='hotelapp.room'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='status',
            field=models.CharField(default='Not Book', max_length=50),
        ),
    ]
