# Generated by Django 5.2.1 on 2026-02-05 19:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotelapp', '0006_payment_rid_alter_booking_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='id',
        ),
        migrations.AlterField(
            model_name='booking',
            name='bid',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='payment',
            name='rid',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='hotelapp.room'),
        ),
    ]
