# Generated by Django 5.2.1 on 2026-02-05 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotelapp', '0007_remove_booking_id_alter_booking_bid_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='paid',
            field=models.CharField(max_length=10),
        ),
    ]
