# Generated by Django 5.2.1 on 2026-02-06 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotelapp', '0008_alter_payment_paid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payment',
            name='id',
        ),
        migrations.AlterField(
            model_name='payment',
            name='pid',
            field=models.IntegerField(default=1, primary_key=True, serialize=False),
        ),
    ]
