# Generated by Django 5.2.1 on 2026-02-06 08:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hotelapp', '0009_remove_payment_id_alter_payment_pid'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Payment',
            new_name='Payments',
        ),
    ]
