# Generated by Django 5.2.1 on 2026-02-06 08:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotelapp', '0010_rename_payment_payments'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pid', models.IntegerField()),
                ('amount', models.IntegerField()),
                ('payment_mode', models.CharField(max_length=50)),
                ('paid', models.CharField(max_length=10)),
                ('payment_date', models.DateField()),
                ('bid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hotelapp.booking')),
                ('rid', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='hotelapp.room')),
            ],
        ),
        migrations.DeleteModel(
            name='Payments',
        ),
    ]
