# Generated by Django 5.2.1 on 2026-02-06 08:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotelapp', '0011_payment_delete_payments'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payment',
            name='id',
        ),
        migrations.AlterField(
            model_name='payment',
            name='pid',
            field=models.IntegerField(default=0, primary_key=True, serialize=False),
        ),
        migrations.CreateModel(
            name='Payments',
            fields=[
                ('pid', models.IntegerField(default=0, primary_key=True, serialize=False)),
                ('amount', models.IntegerField()),
                ('payment_mode', models.CharField(max_length=50)),
                ('paid', models.CharField(max_length=10)),
                ('payment_date', models.DateField()),
                ('bid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hotelapp.booking')),
                ('rid', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='hotelapp.room')),
            ],
        ),
    ]
