# Generated by Django 5.2.1 on 2026-02-06 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotelapp', '0012_remove_payment_id_alter_payment_pid_payments'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='pid',
            field=models.IntegerField(default=1, primary_key=True, serialize=False),
        ),
        migrations.DeleteModel(
            name='Payments',
        ),
    ]
