# Generated by Django 5.2.1 on 2026-02-06 16:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotelapp', '0013_alter_payment_pid_delete_payments'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='gid',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='hotelapp.guest'),
        ),
    ]
