# Generated by Django 5.2.1 on 2026-02-07 06:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotelapp', '0014_payment_gid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payment',
            name='gid',
        ),
        migrations.AlterField(
            model_name='booking',
            name='total_day',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
